### ISSUE TITLE
Consider upgrading to RxDockerClient

### ISSUE THREAD

**Issue by arun-gupta** [AdityaGupta1/mobycraft#12]
More details at https://github.com/shekhargulati/rx-docker-client

**Comment by AdityaGupta1** [comment]
Decided to stick with Docker-Java

**Comment by arun-gupta** [comment]
Docker-Java is a lot more heavily used. RxDockerClient comes with quite a bit of dependencies as well (although not as many as Docker-Java).

In addition, there was a concern about the pace of development of RxDockerClient.
